### ISSUE TITLE
Super O2 tanks not craftable

### ISSUE THREAD

**Issue by DocHuzz** [NFINIT-Development/Astroblock2#15]
Attempted to craft super O2 tank with a filled, partially filled, and a heavy O2 tank.  Used different colored topped tanks in all these configurations as well.  None of these recipes worked for crafting the super O2 tank except for the brown topped empty tank.
Super tanks can be made into Supreme tanks and these can be crafted into Omega tanks.

**Comment by Enderized** [comment]
The Heavy Oxygen Tank you mention is red, not brown.

Issue probably related to the fact, that beside the original
Green - Light
Orange - Medium and
Red - Heavy  Oxygen Tanks from Galacticraft Core, the extra colored variations from Extra Planets do exists, which get not respected by the GalaxySpace Mod which brings the Supreme and Omega Tanks.

simply put: GalaxySpace does not support ExtraPlanets Oxygen Tanks by default for it's recipes but only uses the original ones from Galacticraft Core.

**Comment by knoxhack** [comment]
Removed all Extra planet tanks on version 1.3.0, they all broken
