### ISSUE TITLE
Mods?

### ISSUE THREAD

**Issue by Nicocraft05** [NFINIT-Development/Astroblock2#16]
Why have so few mods on this modpack, why not have put Mekanism back?
And why have you installed refined storage and not applied.
Applied is life?
Why not have just one magic mod?

**Comment by DocHuzz** [comment]
Astroblock is a tech series, not a magic modpack.  You can add mods if you like, but Knox has his own system and vision for this series.

**Comment by knoxhack** [comment]
invalid issue
