### ISSUE TITLE
GalacticraftCore & MO:LE - Mining Moon Rock with the Omnitool crashes the Client

### ISSUE THREAD

**Issue by Enderized** [NFINIT-Development/Astroblock2#23]
Happens MP aswell as SP. See Title.

https://pastebin.com/wAvdT6Eu Crashlog MP
https://pastebin.com/g4U3RJD3 Crashlog SP

MatterOverdrive-1.12.2-0.7.1.0-universal.jar
GalacticraftCore-1.12.2-4.0.2.280.jar

AstroBlock 2 v1.2.0

**Comment by knoxhack** [comment]
Removed the Omni tool from the game in version 1.3.0, we cant update to newer versions of matter overdrive. won't be fixed
