### ISSUE TITLE
Unable to visit other star systems (Barnard C, Proxima B)

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Astroblock2#25]
After researching all available research papers, I cannot see the additional stars/planets in the galaxy map (second screenshot). The map should look like in the first screenshot and the extra stars available when clicking on the "Sol" button, which opens the star selection list to the right. In AstroBlock 2 the little yellow triangle  in the Sol button is missing.

The reason for the missing star systems is probably the option B:enableNewGalaxyMap=false which by default is true in my test install of Galacticraft and GalaxySpace where the first screenshot was taken.

![GalaxySpaceMap](https://user-images.githubusercontent.com/4916644/91377119-f11b9100-e81e-11ea-858b-4ea36eb24222.png)

![AstroBlock2Map](https://user-images.githubusercontent.com/4916644/91378137-01803b80-e820-11ea-88b9-c6ea94227054.png)

**Comment by knoxhack** [comment]
Those planets are actually in the same screen as the rest of the Milky Way, you just gotta scroll over and zoom out to see them
