### ISSUE TITLE
Can't find dungeon on Nibiru, villages are in the air

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Astroblock2#27]
I'm trying to find a dungeon on Nibiru, but all I find are these shafts made from dungeon bricks but no actual dungeon. Tried both the server and SP. I made a testpack with More Planets where I found a dungeon on Nibiru, where the hole leading to the dungeon looked smaller, but the planet also looked quite different visually in this test pack and the villages were properly on the ground instead of floating in the air as in the Astroblock2 modpack.

![image](https://user-images.githubusercontent.com/4916644/91705369-23a9ee80-eb7d-11ea-972e-767257d64dce.png)

**Comment by knoxhack** [comment]
Apparently the current version that we are using has this bug, but the dev release a fix 4 days ago. I'll update it on next update.

https://www.curseforge.com/minecraft/mc-mods/galacticraft-add-on-more-planets/files/3043460

Change Log
+ Added Shield Generator recipe, Closed #65
+ Added "Enable Nibiru Infected Spore suffocation for mobs" config, Implemented #82
* Now Required SteveKunG's Lib 1.1.7
* GC Dungeon Locator should get correct MP Dungeon location
* Renamed Ore Gen configs
* Minor fix to Shield Generator screen size
* Fixed crash when right click machines with battery
* Fixed Nibiru Dungeon failed to generated
* Fixed performance issue with LivingUpdate/WeatherTick events, Closed #95
- Removed Saturation Effect from Cheese Milk Fluid, Closed #83

**Comment by knoxhack** [comment]
Fixed in 1.5.1
