### ISSUE TITLE
Turrets SP v MP

### ISSUE THREAD

**Issue by Kylar1014** [NFINIT-Development/Astroblock2#3]
Turrets are unbreakable in Single Player but we can break them in Multiplayer. Not sure if this is a bug but it would seem like you would want the same experience on both sides.

**Comment by Kylar1014** [comment]
Okay, so update, the turrets on the ships are unbreakable while the turrets on the small round satellite things are breakable. So, this might not be a bug.

**Comment by knoxhack** [comment]
Changed turrets in version 0.4.x
