### ISSUE TITLE
Lighting on Starting Ship (Intentional?)

### ISSUE THREAD

**Issue by TLomon** [NFINIT-Development/Astroblock2#32]
On top of the world gen issue (#31), zombies spawned on the starter ship. This might be intentional as it was in the side engine-pod sections. 

North side, lower level. 

I can not for the life of me find what dark spot they may be spawning on. Lightning seems appropriate in the entire area. Maybe during initial load before the ship is fully formed? They appear to be centered at the west end with 2 blocks in a different chunk.

**Comment by knoxhack** [comment]
were there 2 zombies exactly?

**Comment by TLomon** [comment]
Yes, two exactly.

**Comment by TLomon** [comment]
I should add. I created multiple worlds and it was always two zombies.

**Comment by knoxhack** [comment]
yeah, I think there were copied with the structure

**Comment by TLomon** [comment]
Fixed in 1.6.1. (Please let me know if you would rather close tickets yourself.)
