### ISSUE TITLE
Astroblock 2: Two -Xmx arguments in JVM string, 2nd overrides the first

### ISSUE THREAD

**Issue by MBfromOK** [NFINIT-Development/Astroblock2#37]
I was having lots of issues with lag, I had 6Gb of RAM allocated and was seeing it max out while having a lag spike, I exited back to the JAR launcher and changed the game profile to use 8Gb of RAM, game played smoothly.

I exited the game and set the twitch profile to use 8Gb of RAM, today I relaunched and started playing thinking that it was preset... After a few minutes the lag started, Checking the F3 screen max RAM is 6144MB RAM... Exited the game and checked twitch, set to 8Gb, clicked to play and edited the profile where I saw this:

```
-Xmx8198m -Xms256m -XX:PermSize=256m
```

Launched the Game, F3 shows 6144MB max ram
Exited and checked whole JVM string where I found this:

```
-Duser.country=US -Xmx6G -XX:+UnlockExperimentalVMOptions
```

**Comment by knoxhack** [comment]
I don't really see what the problem is, it doesn't seem related to the modpack this seems like a Twitch Launcher bug

**Comment by MBfromOK** [comment]
You are correct, my bad... 

I went to the actual settings page for Minecraft in Twitch and found an additional parameters box where ```-Xmx6G``` was the first thing listed.
