### ISSUE TITLE
Quest didn't register the finished Tier 3 Rocket (with 54 storage space)

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Astroblock2#5]
To reproduce: I made the T3 rocket in the Rocket Assembly gui, but added 3 vanilla chests in the green boxes. This is a Glacticraft method of adding additional inventory slots in the rocket.

The info of the rocket displays as:
Tier 3 Rocket
Storage Space: 54

**Comment by knoxhack** [comment]
Fixed in 0.4.2
