### ISSUE TITLE
Quest "Tomato Seeds", bonemealed grass not dropping seeds

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Astroblock2#6]
The problem with the quest "Tomato Seeds" is that bonemeal on grass creates vanilla grass which when broken only drops wheat seeds. Only the XL food mod grass drops XL food mod seeds like the ones required by the quest. This special grass generates inside hollow asteroids and so you can only get the xl food mod seeds from there, but of course the number is quite limited.

**Comment by knoxhack** [comment]
Fixed in 0.4.2
