### ISSUE TITLE
Malsis doors reading incorrectly in WAILA

### ISSUE THREAD

**Issue by DocHuzz** [NFINIT-Development/Astroblock2#7]
![2020-08-10_13 01 34](https://user-images.githubusercontent.com/4410570/89826858-d958c300-db24-11ea-8df4-7a8320cfc41d.png)
Looking at this door on the starter craft shows Grass seeds instead of what the item actually is.  AB2 V0.3.0

**Comment by knoxhack** [comment]
Fixed in 0.4.2
